export enum StatusCodeEnums {
  OK = 'OK',
  UNEXPECTED = 'UNEXPECTED',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE ENTITY',
  INVALID_CREDENTIALS = 'INVALID CREDENTIALS',
  USER_EXISTS = 'USER EXISTS',
  COMPANY_EXISTS = 'COMPANY EXISTS',
  INVALID_TOKEN = 'INVALID TOKEN',
  NOT_FOUND = 'NOT FOUND',
  UNATHORIZED = 'UNAUTHORIZED',
}
